"""Initial migration with all models

Revision ID: fcf637132d14
Revises: 
Create Date: 2026-01-12 02:37:34.876464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf637132d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUPPORT', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_admin_email'), ['email'], unique=True)

    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('pib', sa.String(length=20), nullable=True),
    sa.Column('maticni_broj', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='supplierstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pib')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_status'), ['status'], unique=False)

    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pib', sa.String(length=20), nullable=True),
    sa.Column('maticni_broj', sa.String(length=20), nullable=True),
    sa.Column('adresa_sedista', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'CANCELLED', name='tenantstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pib')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_status'), ['status'], unique=False)

    op.create_table('service_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('working_hours_json', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coverage_radius_km', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('has_separate_inventory', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_location_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_location_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('service_representative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('jmbg', sa.String(length=13), nullable=True),
    sa.Column('broj_licne_karte', sa.String(length=20), nullable=True),
    sa.Column('datum_rodjenja', sa.Date(), nullable=True),
    sa.Column('adresa', sa.String(length=300), nullable=True),
    sa.Column('grad', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('lk_front_url', sa.String(length=500), nullable=True),
    sa.Column('lk_back_url', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='representativestatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['platform_admin.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_representative', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_representative_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_representative_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subscription_payment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_proof_url', sa.String(length=500), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['platform_admin.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_payment_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('supplier_listing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model_compatibility', sa.Text(), nullable=True),
    sa.Column('part_category', sa.String(length=50), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('quality_grade', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('min_order_qty', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_listing', schema=None) as batch_op:
        batch_op.create_index('ix_listing_brand_category', ['brand', 'part_category'], unique=False)
        batch_op.create_index('ix_listing_supplier_active', ['supplier_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_listing_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_listing_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'email', name='uq_supplier_user_email')
    )
    with op.batch_alter_table('supplier_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_user_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('tenant_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'TECHNICIAN', 'RECEPTIONIST', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_user_email')
    )
    with op.batch_alter_table('tenant_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_user_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', name='auditaction'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_tenant_entity', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('phone_listing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('imei', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'POOR', name='phonecondition'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_currency', sa.String(length=3), nullable=True),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_contact', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('sales_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sales_currency', sa.String(length=3), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('sold_to', sa.String(length=100), nullable=True),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['service_location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_listing_sold'), ['sold'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_listing_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_phone_location_sold', ['location_id', 'sold'], unique=False)
        batch_op.create_index('ix_phone_tenant_sold', ['tenant_id', 'sold'], unique=False)

    op.create_table('service_ticket',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('imei', sa.String(length=20), nullable=True),
    sa.Column('device_condition', sa.Text(), nullable=True),
    sa.Column('device_password', sa.String(length=50), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'DIAGNOSED', 'IN_PROGRESS', 'WAITING_PARTS', 'READY', 'DELIVERED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('estimated_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('warranty_days', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['tenant_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['tenant_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['service_location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ticket_number', name='uq_tenant_ticket_number')
    )
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_ticket_access_token'), ['access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_ticket_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_ticket_location_status', ['location_id', 'status'], unique=False)
        batch_op.create_index('ix_ticket_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ticket_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('spare_part',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('part_category', sa.Enum('DISPLAY', 'BATTERY', 'CHARGING_PORT', 'CAMERA', 'SPEAKER', 'MICROPHONE', 'BUTTON', 'FRAME', 'BACK_COVER', 'MOTHERBOARD', 'OTHER', name='partcategory'), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('quality_grade', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_stock_level', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('public_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PARTNER', 'PUBLIC', name='partvisibility'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['service_location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.create_index('ix_part_brand_model', ['brand', 'model'], unique=False)
        batch_op.create_index('ix_part_tenant_visibility', ['tenant_id', 'visibility'], unique=False)
        batch_op.create_index('ix_part_visibility_category', ['visibility', 'part_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_visibility'), ['visibility'], unique=False)

    op.create_table('user_location',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('can_manage', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['service_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    op.create_table('part_order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_tenant_id', sa.Integer(), nullable=False),
    sa.Column('buyer_location_id', sa.Integer(), nullable=True),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('seller_type', sa.Enum('SUPPLIER', 'TENANT', name='sellertype'), nullable=False),
    sa.Column('seller_supplier_id', sa.Integer(), nullable=True),
    sa.Column('seller_tenant_id', sa.Integer(), nullable=True),
    sa.Column('service_ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'CONFIRMED', 'REJECTED', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('buyer_notes', sa.Text(), nullable=True),
    sa.Column('seller_notes', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_location_id'], ['service_location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['tenant_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_supplier_id'], ['supplier.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_order', schema=None) as batch_op:
        batch_op.create_index('ix_order_buyer_status', ['buyer_tenant_id', 'status'], unique=False)
        batch_op.create_index('ix_order_seller_supplier', ['seller_supplier_id', 'status'], unique=False)
        batch_op.create_index('ix_order_seller_tenant', ['seller_tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_order_buyer_tenant_id'), ['buyer_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_part_order_status'), ['status'], unique=False)

    op.create_table('part_order_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_listing_id', sa.BigInteger(), nullable=True),
    sa.Column('spare_part_id', sa.BigInteger(), nullable=True),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['part_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_listing_id'], ['supplier_listing.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_order_item_order_id'), ['order_id'], unique=False)

    op.create_table('part_order_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('read_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['part_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_order_message', schema=None) as batch_op:
        batch_op.create_index('ix_message_order_created', ['order_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_order_message_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part_order_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_order_message_order_id'))
        batch_op.drop_index('ix_message_order_created')

    op.drop_table('part_order_message')
    with op.batch_alter_table('part_order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_order_item_order_id'))

    op.drop_table('part_order_item')
    with op.batch_alter_table('part_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_order_status'))
        batch_op.drop_index(batch_op.f('ix_part_order_order_number'))
        batch_op.drop_index(batch_op.f('ix_part_order_buyer_tenant_id'))
        batch_op.drop_index('ix_order_seller_tenant')
        batch_op.drop_index('ix_order_seller_supplier')
        batch_op.drop_index('ix_order_buyer_status')

    op.drop_table('part_order')
    op.drop_table('user_location')
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_visibility'))
        batch_op.drop_index(batch_op.f('ix_spare_part_tenant_id'))
        batch_op.drop_index('ix_part_visibility_category')
        batch_op.drop_index('ix_part_tenant_visibility')
        batch_op.drop_index('ix_part_brand_model')

    op.drop_table('spare_part')
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_tenant_status')
        batch_op.drop_index('ix_ticket_tenant_created')
        batch_op.drop_index('ix_ticket_location_status')
        batch_op.drop_index(batch_op.f('ix_service_ticket_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_location_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_access_token'))

    op.drop_table('service_ticket')
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.drop_index('ix_phone_tenant_sold')
        batch_op.drop_index('ix_phone_location_sold')
        batch_op.drop_index(batch_op.f('ix_phone_listing_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_phone_listing_sold'))

    op.drop_table('phone_listing')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_created')
        batch_op.drop_index('ix_audit_tenant_entity')
        batch_op.drop_index('ix_audit_tenant_created')
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('tenant_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_user_tenant_id'))

    op.drop_table('tenant_user')
    with op.batch_alter_table('supplier_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_user_supplier_id'))

    op.drop_table('supplier_user')
    with op.batch_alter_table('supplier_listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_listing_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_listing_is_active'))
        batch_op.drop_index('ix_listing_supplier_active')
        batch_op.drop_index('ix_listing_brand_category')

    op.drop_table('supplier_listing')
    with op.batch_alter_table('subscription_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_payment_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_payment_status'))

    op.drop_table('subscription_payment')
    with op.batch_alter_table('service_representative', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_representative_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_representative_status'))

    op.drop_table('service_representative')
    with op.batch_alter_table('service_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_location_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_location_city'))

    op.drop_table('service_location')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_status'))
        batch_op.drop_index(batch_op.f('ix_tenant_slug'))

    op.drop_table('tenant')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_slug'))

    op.drop_table('supplier')
    with op.batch_alter_table('platform_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_admin_email'))

    op.drop_table('platform_admin')
    # ### end Alembic commands ###
